apiVersion: apps/v1
kind: Deployment
metadata:
  name: bghn7hu7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bghn7hu7
  template:
    metadata:
      labels:
        app: bghn7hu7
    spec:
      containers:
      - image: okteto.dev/bghn7hu7:latest
        name: bghn7hu7
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "27e1f9e1-3d1d-45ad-be1a-37a517dec5f3"
        - name: Vless_Path
          value: "/edrfccvx"
        - name: Vmess_UUID
          value: "27e1f9e1-3d1d-45ad-be1a-37a517dec5f3"
        - name: Vmess_Path
          value: "/34dcqas"
        - name: Share_Path
          value: "/share233"
