apiVersion: apps/v1
kind: Deployment
metadata:
  name: dofuner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dofuner
  template:
    metadata:
      labels:
        app: dofuner
    spec:
      containers:
      - image: okteto.dev/dofuner:latest
        name: dofuner
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "clipchamp.com"
        - name: Vless_UUID
          value: "d0cde382-a5df-477a-8b55-dca679d96050"
        - name: Vless_Path
          value: "/erfdr5t6"
        - name: Vmess_UUID
          value: "d0cde382-a5df-477a-8b55-dca679d96050"
        - name: Vmess_Path
          value: "/e3wdef4"
        - name: Share_Path
          value: "/share233"
