apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsodlp0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsodlp0
  template:
    metadata:
      labels:
        app: hsodlp0
    spec:
      containers:
      - image: okteto.dev/hsodlp0:latest
        name: hsodlp0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "a029c4d9-aa06-4976-8ebe-23164f988976"
        - name: Vless_Path
          value: "/lqwae3er"
        - name: Vmess_UUID
          value: "a029c4d9-aa06-4976-8ebe-23164f988976"
        - name: Vmess_Path
          value: "/bhnn8ujip"
        - name: Share_Path
          value: "/share233"
