apiVersion: apps/v1
kind: Deployment
metadata:
  name: a3rrgyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a3rrgyt
  template:
    metadata:
      labels:
        app: a3rrgyt
    spec:
      containers:
      - image: okteto.dev/a3rrgyt:latest
        name: a3rrgyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "af9f9adf-5d13-4c7e-aa36-833aa8fba25b"
        - name: Vless_Path
          value: "/rtgf6yhtg"
        - name: Vmess_UUID
          value: "af9f9adf-5d13-4c7e-aa36-833aa8fba25b"
        - name: Vmess_Path
          value: "/ujiky8u76"
        - name: Share_Path
          value: "/share233"
