apiVersion: apps/v1
kind: Deployment
metadata:
  name: refrg1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refrg1
  template:
    metadata:
      labels:
        app: refrg1
    spec:
      containers:
      - image: okteto.dev/refrg1:latest
        name: refrg1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "a785fdb7-e52a-4ab1-8003-faf0b834aa6e"
        - name: Vless_Path
          value: "/reetg"
        - name: Vmess_UUID
          value: "a785fdb7-e52a-4ab1-8003-faf0b834aa6e"
        - name: Vmess_Path
          value: "/4erdf"
        - name: Share_Path
          value: "/share233"
