apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtgfbvb80
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtgfbvb80
  template:
    metadata:
      labels:
        app: rtgfbvb80
    spec:
      containers:
      - image: okteto.dev/rtgfbvb80:latest
        name: rtgfbvb80
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "clipchamp.com"
        - name: Vless_UUID
          value: "c567a999-e663-4bf0-981f-7051bd3fe63a"
        - name: Vless_Path
          value: "/doer45t"
        - name: Vmess_UUID
          value: "c567a999-e663-4bf0-981f-7051bd3fe63a"
        - name: Vmess_Path
          value: "/ythg7uy"
        - name: Share_Path
          value: "/share233"
