apiVersion: apps/v1
kind: Deployment
metadata:
  name: vfrd43s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vfrd43s
  template:
    metadata:
      labels:
        app: vfrd43s
    spec:
      containers:
      - image: okteto.dev/vfrd43s:latest
        name: vfrd43s
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "d0813a9a-1e40-4a8e-ae17-5ea9ff1e0e5d"
        - name: Vless_Path
          value: "/okjnn8uu"
        - name: Vmess_UUID
          value: "d0813a9a-1e40-4a8e-ae17-5ea9ff1e0e5d"
        - name: Vmess_Path
          value: "/oki9juh9"
        - name: Share_Path
          value: "/share233"
