apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkijngg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkijngg
  template:
    metadata:
      labels:
        app: mkijngg
    spec:
      containers:
      - image: okteto.dev/mkijngg:latest
        name: mkijngg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "canva.com"
        - name: Vless_UUID
          value: "97be42cf-3115-49ed-af73-03c0555bd827"
        - name: Vless_Path
          value: "/enr889tfc"
        - name: Vmess_UUID
          value: "97be42cf-3115-49ed-af73-03c0555bd827"
        - name: Vmess_Path
          value: "/n6gythhy9"
        - name: Share_Path
          value: "/share233"
