apiVersion: v1
kind: Service
metadata:
  name: bghn7hu7
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "bghn7hu7"
    port: 8080
  selector:
    app: bghn7hu7
