apiVersion: v1
kind: Service
metadata:
  name: rtgfbvb80
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "rtgfbvb80"
    port: 8080
  selector:
    app: rtgfbvb80
