apiVersion: v1
kind: Service
metadata:
  name: vfrd43s
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "vfrd43s"
    port: 8080
  selector:
    app: vfrd43s
