apiVersion: v1
kind: Service
metadata:
  name: hsodlp0
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hsodlp0"
    port: 8080
  selector:
    app: hsodlp0
