apiVersion: v1
kind: Service
metadata:
  name: refrg1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "refrg1"
    port: 8080
  selector:
    app: refrg1
