apiVersion: v1
kind: Service
metadata:
  name: a3rrgyt
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "a3rrgyt"
    port: 8080
  selector:
    app: a3rrgyt
